#!/bin/bash

make && make bonus

# This script generates a random set of numbers and tests the push_swap program with them.
# It also checks the output of the program with a checker program.

# a random number between 1 to 1000 is generated
random_size=$(shuf -i 1-1000 -n 1)
# a list with the size of random size is generated by random numbers between -2000 to 2000
ARG=$(seq -2000 2000 | shuf -n $random_size)

echo $ARG >> tested_numbers.txt
echo "" >> tested_numbers.txt
echo " "
./push_swap $ARG
echo " "
echo "number of values: "
echo $random_size
echo " "
echo "instruction number: "
./push_swap $ARG | wc -l
echo " "
echo "check result: "
./push_swap $ARG | ./checker $ARG